### ISSUE TITLE
回溯时循环条件好像有点问题

### ISSUE THREAD

**Issue by ymcvalu** [cj1128/myers-diff#1]
https://github.com/fate-lovely/myers-diff/blob/4613bf7fbf0ba327d5e9069d364e78b721cca17e/main.go#L157
我使用
`A
B
C
D
E`
和
`A
B
D
E`测试的时候，结果是
`-A
B
C`，定位到错误应该是在回溯的时候，这里d==0的时候也应该考虑进去，如果两个文本前面内容相同，需要在d==0的时候执行添加MOV的操作。在https://github.com/pkg/diff/blob/7e42a82532c282d39d727ace02bfdef801c6db2c/myers.go#L71 这个实现里面就有考虑d==0的情况

**Comment by cj1128** [comment]
@ymcvalu 你是对的，我更新了代码，修复了这个问题~
